export const NAIL_KEYWORD_EN_DICTIONARY: Record<string, string> = {
  네일: 'Nail',
  페디: 'Pedi',
  패디: 'Pedi',
  젤: 'Gel',
  프렌치: 'French',
  딥프렌치: 'Deep French',
  둥근프렌치: 'Round French',
  시럽: 'Syrup',
  글리터: 'Glitter',
  파츠: 'Charms',
  스톤: 'Stone',
  스와로브스키: 'Swarovski',
  큐빅: 'Cubic',
  진주: 'Pearl',
  체인: 'Chain',
  그라데이션: 'Ombre',
  옴브레: 'Ombre',
  솜사탕: 'Cotton Candy',
  마블: 'Marble',
  대리석: 'Marble Stone',
  자석: 'Magnetic',
  고양이눈: 'Cat Eye',
  마그넷: 'Magnet',
  얼음: 'Ice',
  유리알: 'Glass Bead',
  물방울: 'Water Drop',
  엠보: '3D Art',
  '3D': '3D',
  입체: '3D Art',
  드로잉: 'Drawing',
  라인: 'Line Art',
  체크: 'Plaid',
  트위드: 'Tweed',
  니트: 'Knit',
  호피: 'Leopard',
  레오파드: 'Leopard',
  플라워: 'Floral',
  생화: 'Floral',
  꽃: 'Flower',
  동물: 'Animal Print',
  캐릭터: 'Character',
  스마일: 'Smile',
  리본: 'Ribbon',
  나비: 'Butterfly',
  하트: 'Heart',
  별: 'Star',
  달: 'Moon',
  우주: 'Space',
  은하수: 'Milky Way',
  오로라: 'Aurora',
  홀로그램: 'Hologram',
  파우더: 'Powder',
  미러: 'Mirror',
  머메이드: 'Mermaid',
  호일: 'Foil',
  금박: 'Gold Foil',
  은박: 'Silver Foil',
  자개: 'Shell',
  뉘앙스: 'Nuance',
  치크: 'Blush',
  시스루: 'Sheer',
  테라조: 'Terrazzo',
  아가일: 'Argyle',
  도트: 'Dot',
  수채화: 'Watercolor',
  잉크: 'Ink',
  풀컬러: 'Solid Color',
  숏: 'Short',
  미디엄: 'Medium',
  롱: 'Long',
  연장: 'Extension',
  팁: 'Tip',
  아크릴: 'Acrylic',
  스퀘어: 'Square',
  라운드: 'Round',
  오발: 'Oval',
  아몬드: 'Almond',
  스틸레토: 'Stiletto',
  코핀: 'Coffin',
  발레리나: 'Ballerina',
  귀여운: 'Cute',
  큐티: 'Cute',
  시크: 'Chic',
  모던: 'Modern',
  화려한: 'Glam',
  블링블링: 'Bling',
  심플: 'Simple',
  깔끔: 'Clean',
  단정: 'Neat',
  여리여리: 'Soft',
  청순: 'Pure',
  힙한: 'Hip',
  유니크: 'Unique',
  빈티지: 'Vintage',
  레트로: 'Retro',
  키치: 'Kitsch',
  우아한: 'Elegant',
  고급스러운: 'Luxury',
  엔틱: 'Antique',
  섹시: 'Sexy',
  걸코어: 'Girlcore',
  발레코어: 'Balletcore',
  올드머니: 'Old Money',
  '시크 파스텔': 'Chic Pastel',
  레드: 'Red',
  핑크: 'Pink',
  코랄: 'Coral',
  오렌지: 'Orange',
  옐로우: 'Yellow',
  노랑: 'Yellow',
  그린: 'Green',
  초록: 'Green',
  블루: 'Blue',
  파랑: 'Blue',
  네이비: 'Navy',
  퍼플: 'Purple',
  보라: 'Purple',
  라벤더: 'Lavender',
  화이트: 'White',
  블랙: 'Black',
  그레이: 'Gray',
  실버: 'Silver',
  골드: 'Gold',
  베이지: 'Beige',
  누드: 'Nude',
  브라운: 'Brown',
  파스텔: 'Pastel',
  네온: 'Neon',
  비비드: 'Vivid',
  형광: 'Fluorescent',
  맑은: 'Clear',
  딥한: 'Deep',
  카키: 'Khaki',
  올리브: 'Olive',
  버건디: 'Burgundy',
  와인: 'Wine',
  머스타드: 'Mustard',
  민트: 'Mint',
  소라: 'Sky Blue',
  하늘: 'Sky Blue',
  봄: 'Spring',
  여름: 'Summer',
  가을: 'Autumn',
  겨울: 'Winter',
  웨딩: 'Wedding',
  신부: 'Bride',
  결혼: 'Wedding',
  하객: 'Wedding Guest',
  데이트: 'Date',
  소개팅: 'Blind Date',
  면접: 'Interview',
  오피스: 'Office',
  출근: 'Work',
  직장인: 'Office Worker',
  바캉스: 'Vacation',
  휴양지: 'Resort',
  여행: 'Travel',
  바다: 'Beach',
  페스티벌: 'Festival',
  파티: 'Party',
  연말: 'Year End',
  크리스마스: 'Christmas',
  할로윈: 'Halloween',
  명절: 'Holiday',
  졸업: 'Graduation',
  입학: 'School Entrance',
}
